name: personal_training_app
description: Final Year Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  flutter_bloc: ^8.1.2
  firebase_auth: ^4.2.9
  logger: ^1.1.0
  flutter_svg: ^2.0.2
  flutter_secure_storage: ^8.0.0
  cached_network_image: ^3.2.3
  camera: ^0.10.3+1
  dropdown_button2: ^2.0.0
  equatable: ^2.0.5
  path_provider: ^2.0.13
  gallery_saver: ^2.3.2
  video_player: ^2.5.3
  chewie: ^1.4.0
  http:
  dio: ^5.0.2
  cloud_firestore: ^4.4.5
  multi_select_flutter: ^4.1.3
  intl:
  fl_chart: ^0.61.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/icons/
     - assets/placeholders/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Regular.ttf
         - asset: assets/fonts/Montserrat-Bold.ttf
         - asset: assets/fonts/Montserrat-Medium.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
